### PR TITLE
Add option for pattern-based hero headers.

### PR DESCRIPTION
**Pull request by tobie**
Setting the header.overlay_pattern option to true makes
the pattern repeat itself. Plays well with filters, too.

patterns

### CODE REVIEW

**Comment by tobie** [comment]
The other option is to make `overlay_pattern` take the URL of the image.

**Comment by tobie** [comment]
Hey, just curious if you're interested in this at all (either using a boolean `overlay_pattern` or one that returns a URL) and if you'd wan't me to rebase so this can be merged. Else I'll just close this.

**Comment by mmistakes** [comment]
Was hesitant to include it as I don't want to over stuff everything with so many options. You can leave it open and see if anyone chimes in if this sort of thing is useful.

**Comment by vg** [comment]
@tobie can you provide an unminified version of assets/css/main.css
I am not able to do a diff to see the changes

**Comment by tobie** [comment]
@vg that file's generated from assets/_scss/_page.scss.

**Comment by vlsi** [comment]
Just in case: I would like to have just "linear gradient" background, so regarding

> if anyone chimes in if this sort of thing is useful

I would say enabling "pattern backgound" and similar features would be valuable.

**Pull request closed without merging**
