### PR TITLE
New comment.

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field   | Content                          |
| ------- | -------------------------------- |
| message | testing comments                 |
| name    | aaa aa                           |
| email   | c3d91d58db35f15d98cc8f737bca8715 |
| url     |                                  |
| hidden  |                                  |
| date    | 2017-05-08T06:35:22.005Z         |

### CODE REVIEW

**Comment by jhabdas** [comment]
@mmistakes just an observation. i'm not sure I'm going to be able to find that pull I was looking for now ^^

**Comment by mmistakes** [comment]
@jhabdas Huh?

**Comment by jhabdas** [comment]
Signal v. Noise. I'm moving to the ChangeLog instead. Perhaps Edwardo or contributor could use a label for automated PR to aid in filtering them out.

screen shot 2017-05-09 at 8 11 57 pm

**Comment by mmistakes** [comment]
If you ask me, the real noise comes more from the mistaken PR's every time someone new to Git tries to update their blog with this theme.

**Comment by jhabdas** [comment]
> If you ask me, the real noise comes more from the mistaken PR's every time someone new to Git tries to update their blog with this theme.

I've been noticing a bit of that lately both on themes and repos in general which attract newcomers. I wonder if there's an opportunity for GH to surface an option for help mitigate that behavior now on the horizon. Their support team is fairly responsive last time I shot them a note via the interface. They don't share their roadmaps publicly (I asked), but they may be able to provide some alternatives to help you focus on your craft.

**Comment by mmistakes** [comment]
I'm not too concerned about it. More of an observation than a hindrance for me.

**Comment by jhabdas** [comment]
Right on. By the way, found what I was looking for. Wasn't even in the right repo 🤦‍♂️ https://github.com/jekyll/jekyll-seo-tag/pull/166#discussion_r109551241

**Pull request closed without merging**
