### PR TITLE
adding gitlab as a social profile

### PR DESCRIPTION
**Pull request by vg**

### CODE REVIEW

**Comment by jhabdas** [comment]
Outside the scope of this PR, but nonetheless useful, is a [Spanish translation of the `ui-text`](https://github.com/mmistakes/minimal-mistakes/pull/332/files#diff-9f9fee423993fc5143318023f2cd6560R36). Thanks for including that, @vg, but it probably shouldn't be part of this PR.

**Comment by basnijholt** [comment]
Let's merge this!

**Comment by vg** [comment]
@jhabdas The second commit was an error, and was not intended to be a part of the pull request. 
I just discovered that any changes made to your forked repo after a pull request to the master are also included in the pull request. I did not know that would happen, until recently.

**Comment by jhabdas** [comment]
@vg tricky right! I make that mistake all the time. remembering to use branches has helped.

**Comment by mmistakes** [comment]
Closing to keep the theme lean and avoid configuration bloat. The defaults cover the most popular networks, anything else I envisioned being customized by the user.

**Pull request closed without merging**
