### PR TITLE
Allow custom Staticman endpoints

### PR DESCRIPTION
**Pull request by maxime-michel**
As discussed in #1842.

### CODE REVIEW

**Comment by maxime-michel** [comment]
Sure. I saw you initially requested that but I wasn't sure it was what you actually meant. Then I saw an occurrence of `{{ site.comments.disqus.shortname }}`, which made me go for this approach. But sure, I don't mind.

**Comment by mmistakes** [comment]
Sounds good.

In the grand scheme of things it probably doesn't matter. What you have was a good approach since it follows the other comment providers. If there wasn't already `site,staticman` your approach makes the most sense.

**Comment by maxime-michel** [comment]
@mmistakes I don't mean to be spammy but did you get a notification for the changes I pushed right after your comment?

**Comment by mmistakes** [comment]
No didn't get a notification. But I see it now.

**Pull request merged**
