### PR TITLE
Color notices based on skin colors instead of fixed values

### PR DESCRIPTION
**Pull request by tsmanner**
This is an enhancement or feature.

## Summary

This PR replaces the fixed color values of `$dark-gray` and `#fff` used to determine notice foreground and background colors with `$text-color` and  `$background-color`, respectively.  The old values are the defaults for the theme, so the default skin is unaffected.

## Context

I almost always use dark themes for my sites, and notices are very glaring as is:
image

With this PR, it is much easier on the eyes, and the background color changes are more obvious.

<details><summary>Screenshots of all prepackaged skins</summary>

### `minimal_mistakes_skin: "default"`:
image

### minimal_mistakes_skin: "air"
image

### minimal_mistakes_skin: "aqua"
image

### minimal_mistakes_skin: "contrast"
image

### `minimal_mistakes_skin: "dark"`:
image

### minimal_mistakes_skin: "dirt"
image

### minimal_mistakes_skin: "neon"
image

### minimal_mistakes_skin: "mint"
image

### minimal_mistakes_skin: "plum"
image

### minimal_mistakes_skin: "sunrise"
image

</details>

### CODE REVIEW

**Comment by iBug** [comment]
Will you increase the color intensity for notices? As you've probably seen, it doesn't stand out on dark themes. Decreasing the percentage values on lines 20 and 57 to something like 80% and 90% should look better.

**Comment by tsmanner** [comment]
Sure, I didn't mess with any of that, but I'm happy to make some more adjustments since I'm in there already.  I'll post some screenshots along side that change.

**Comment by tsmanner** [comment]
Here goes, I made a couple of changes here to help readability of notices.

First, the link text is darkened slightly (both non-hovered and hovered), because with a slightly darker background, the gray-on-gray links were hard to read.

Second, the background color (line 20) and code background color (line 57) mixes were made into the SCSS variables `$notice-background-mix` and `$code-notice-background-mix`.  Those variables now have default values of 80% and 90%, and replace the hardcoded 90% and 95% from lines 20 and 57.

Third, I went through each skin and adjusted the values for the skins that didn't work well with the defaults.

- default
image
- air 
image
- aqua (adjusted mix back to 90%/95%)
image
- contrast
image
- dark (adjusted mix back to 90%/95%)
image
- dirt
image
- neon (adjusted mix back to 90%/95%)
image
- mint
image
- plum (adjusted mix to 70%/80%)
image
- sunrise
image

**Comment by tsmanner** [comment]
I do have one remaining question: where/how should this change be documented, if at all?  The stuff on the docs page is front-end documentation for the most part, I guess this is more of an issue if someone were to develop a skin and have to figure out what to look for.  Anyway, let me know if you can think of a good place, and I'll be happy to write it up.

**Comment by iBug** [comment]
I think [`docs/_docs/16-stylesheets.md`][1] would be a good place. This repository already has a [CHANGELOG][2] and a [history page][3] (manually maintained) so I wouldn't bother much.

  [1]: https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_docs/16-stylesheets.md
  [2]: https://github.com/mmistakes/minimal-mistakes/blob/master/CHANGELOG.md
  [3]: https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_docs/18-history.md

**Comment by tsmanner** [comment]
I read through the stylesheets doc to see what's in there, I think it doesn't make sense to include explicit documentation of the new variables.  Unless, of course, there's intent to document all or most of the SCSS variables, which would be a different PR.  Only a handful of the color variables are documented, the rest are pretty easy to follow and find.  If a changelog entry is good enough for you all, it's good enough for me.

**Review by iBug — APPROVED** [review]
This is WONDERFUL! It should be ready to merge.

**Pull request merged**
