### PR TITLE
Add TOC anchor history

### PR DESCRIPTION
**Pull request by jhabdas**
Provides ability to copy URL from location bar after clicking a link in the TOC (making deep linking easier). Also rewrites app JS in ES6 (please confirm plug-ins still functional). Note I got rid of the [semicolons](http://theoatmeal.com/comics/semicolon). Not to be hipster, but because it's practical. The updated uglifier dep is pinned in the manifest as it's still considered _experimental_. But it felt worth it since it's only a dev dependency and the benefit to allowing ES6  helps ease JSing for the masses.

### CODE REVIEW

**Comment by mmistakes** [comment]
Do you have a demo of how the TOC anchor history works?

Since I'll have to maintain this bad boy when things break, I'd prefer not mess with ES6 right now. I'm barely competent writing vanilla JS and jQuery and don't want this to be a blocker if things need to be adjusted in the future.

**Comment by jhabdas** [comment]
Funny you should mention that. I was just pulling up a link and got sidetracked. https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/

**Comment by jhabdas** [comment]
Please note the AnchorJS stuff I did not add. That's custom.

**Comment by mmistakes** [comment]
How big is the AnchorJS dependency? If it's small I'd be interested in a PR that adds support for that and the TOC anchors to the URL bar, similar to how you did it on your site... without the ES6 rewrite :wink:

A request came in recently to support it #860

**Comment by jhabdas** [comment]
@mmistakes you got a bot! awww, I want one. happen to have written about it on your site? would love to read about that cute little bot guy there!!!!

**Comment by jhabdas** [comment]
Closed due to age. Will leave the branch intact until I end up doing more housekeeping on GH. Cheers!

**Comment by mmistakes** [comment]
Not much to write up about it. I hooked up [probot/stale](https://github.com/probot/stale) to my GH repo and added a `stale.yml` config file. Done.

**Pull request closed without merging**
