### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by aabiro**

### CODE REVIEW

**Comment by mmistakes** [comment]
You're pushing to the wrong repo. Check your `origin`.

**Comment by aabiro** [comment]
sorry I am trying to merge for the first time here and having some issues :(

**Comment by mmistakes** [comment]
@aabiro Check your remote repo. When you forked it it's probably still pointing to the MM repo. You need to update your remote `origin` to point to your repo.

**Comment by aabiro** [comment]
yes that was it..thanks sry

**Pull request closed without merging**
