### PR TITLE
sidebar: added support for html content

### PR DESCRIPTION
**Pull request by rsaccani**
Hi, I've added the possibility to enter html content in the custom sidebar.

### CODE REVIEW

**Comment by mmistakes** [comment]
Not sure if this is needed. You can already add HTML using `text`. It accepts Markdown which also should accept HTML since Kramdown processes both.

Does this not work?

```html
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "<strong>Here's some HTM.</strong>"
```

**Comment by rsaccani** [comment]
I see. I had problems adding a form (paypal button) using sidebar.text, that's why I made this change. 
Probably it was just a multiline formatting issue. I just tried again with sidebar.text putting everything in a single line and it worked fine.
So, it looks like there's no need for sidebar.html.

**Comment by mmistakes** [comment]
If you use literal line scalar in YAML (e.g. `|`)  multiline HTML should work just fine. I tested this with no issues.

```yaml
sidebar:
  - title: "Another Title"
    text: |
      <table>
        <tr>
          <td>Sample cell 1</td>
          <td>Sample cell 2</td>
        </tr>
      </table>
```

**Comment by RichStone** [comment]
Is there a way to include an HTML piece from the _includes folder using the sidebar?

**Comment by mmistakes** [comment]
@RichStone If you need that sort of flexibility you'll need to hack the theme. I'm pretty sure there is no way to pull in a Jekyll include via YAML Front Matter... at least not without some added logic to the theme.

**Pull request closed without merging**
