### PR TITLE
Update jQuery to 3.5.1

### LINKED ISSUE #2712: Update jQuery to 3.5.1
## Summary

Update jQuery to >= 3.5.0

## Motivation

Removes potential security vulnerabilities (XSS). https://github.com/jquery/jquery/security/advisories

## Drawbacks

Compatibility will need to be tested. https://jquery.com/upgrade-guide/3.5/

### PR DESCRIPTION
**Pull request by magneticflux-**
This is an enhancement or feature.

## Summary

Updates jQuery and replaces `jquery-3.4.1.js` with `jquery-3.5.1.js`.

## Context

Closes #2712

### CODE REVIEW

**Comment by magneticflux-** [comment]
Also consider having the Travis CI build fail gracefully when API keys are unavailable!

Some info: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository (“internal pull requests”). These are considered trustworthy, as only members with write access to the repository can send them.

**Comment by magneticflux-** [comment]
Tests and audits pass:
image

Running `npm install && npm run build:js` modifies some files, should those be updated as well?

**Comment by mmistakes** [comment]
@magneticflux- Yes, run `npm run build:js` and commit `assets/js/main.min.js` so the compiled version is included. As far as I can tell upgrading to jQuery 3.0.5 didn't break anything.

@iBug care to run some quick tests to see if things look good to you?

**Comment by iBug** [comment]
I did a quick search and it looks like there's no worries (but haven't tested it yet).

[jQuery 3.5][1] is a security update that contains only one breaking change regarding how `htmlPrefilter` handles [multiple self-enclosed XHTML tags][2]. I don't see anything depending on that behavior so we can safely expect everything proceeds as normal.

  [1]: https://jquery.com/upgrade-guide/3.5/
  [2]: https://stackoverflow.com/a/62031714/5958455

**Review by mmistakes — APPROVED** [review]

**Pull request merged**
