### PR TITLE
Feature: Incorporate site search into masthead

### PR DESCRIPTION
**Pull request by mmistakes**
- [x] Enable masthead search toggle with `site.search == true` in _config.yml
- [x] Toggle search input with button in masthead (magnifying glass icon)
- [x] Update documentation, add note about `_layout/search.html` and masthead search not playing nice together. Deprecate search layout?

Example:

masthead-search

Ref #1011

### CODE REVIEW

**Comment by ohadschn** [comment]
Wow, nice!!

**Comment by mmistakes** [comment]
@ohadschn Thought you'd might enjoy this early holiday :gift:

**Comment by ohadschn** [comment]
This is like the Hanukkah Miracle all over again!

**Comment by justinrummel** [comment]
Looks Great!

**Pull request merged**
