### PR TITLE
Remove bold and italics to make it searchable

### PR DESCRIPTION
**Pull request by Anteus**
This is an enhancement or feature. 

## Summary

Remove bold and italics that are noted with asterisks (*) to make it searchable with lunr and full text search.

### CODE REVIEW

**Comment by iBug** [comment]
Is this really a problem? HTML is already stripped:

<https://github.com/f7770ad0799b1c847ea35972f1d286e71a1a50ee/minimal-mistakes/blob/master/assets/js/lunr/lunr-store.js#L30>

<https://github.com/f7770ad0799b1c847ea35972f1d286e71a1a50ee/minimal-mistakes/blob/master/assets/js/lunr/lunr-store.js#L41>

**Comment by Anteus** [comment]
The search didn't work without that as the asterisks where around words still eg. *sample*

**Comment by iBug** [comment]
I don't understand. I mean (properly placed) asterisks in **source Markdown** will be rendered into HTML tags `<b>` and `<em>` respectively, which is what *actually* makes text look bold and italic, so there should be no more raw asterisks in the output HTML, which is the script working on.

**Comment by mmistakes** [comment]
It's unclear to me what problem this is solving. Can you link to a repo that is having issues with bold or italic words not being searchable?

As noted by @iBug HTML is already stripped. Stripping asterisks where you have in this PR will remove it from the text... it's not Markdown in this case.

**Comment by Anteus** [comment]
My bad was using [this](https://github.com/solarillion/solarillion.github.io/blob/master/assets/js/lunr/lunr-store.js) modified one to index pages.

**Pull request closed without merging**
