### PR TITLE
Do not include feature rows in TOC

### PR DESCRIPTION
**Pull request by lsolesen**
This is a bug fix.

## Summary

The feature_row should not be included in the TOC

### CODE REVIEW

**Comment by iBug** [comment]
Good spot!

Just for the record, `feature_row`s aren't intended for posts ([ref](https://github.com/mmistakes/minimal-mistakes/issues/2263#issuecomment-531500264)):

> Not sure. Feature blocks weren't designed to be used as you have so that's likely why they misbehave for you.
> 
> They're more for splash pages, not posts with table of Contents.
> 
> Since you're doing images use the gallery helper instead. That's what it's designed for.
> 
> <https://mmistakes.github.io/minimal-mistakes/docs/helpers/#gallery>

**Comment by lsolesen** [comment]
Feature rows works well for posts also. The gallery does not supply btn and
text, so they are also very helpful.

tor. 21. maj 2020 09.49 skrev iBug ♦ <notifications@github.com>:

**Comment by mmistakes** [comment]
Would there be cases where someone would want the feature row headings to appear in the table of contents? If you're adding it as post/page content then I think it's valid to expect it should be reflected in the page hierarchy, especially if they are considered part of the "main" content.

There was an earlier PR to ignore the "Comments" section heading which made sense. Not entirely sure on this one. I can see users wanting them in the TOC. Which means some sort of config flag to enable/disable... which you all know my position on that one ;-)

**Comment by lsolesen** [comment]
@mmistakes I think this should be kept open, or closed with a No Fix?

**Pull request closed without merging**
