### PR TITLE
Improve Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by lucascaton**

### CODE REVIEW

**Comment by mmistakes** [comment]
Is this an improvement over what was done in #824? I'm not familiar with the language to know which reads better. There have been several PR's for this same change and just trying to figure out if this is just a "preference" or if one version is grammatically better.

**Comment by mmistakes** [comment]
Trying to avoid accepting PR's were people keep changing the string to read how they think it should, which seems to be the case with all of the previous PR's.

**Comment by lucascaton** [comment]
Hi @mmistakes, thanks for having a look at this.

The PR you mentioned is pretty much the same, so I'll close mine.
However, that was merged into `development` branch, is it going to be merged into `master` soon?

Thank you.

**Comment by mmistakes** [comment]
It should have been merged into`master`. Will have to investigate why it wasn't. 

If you had time there are a [few text strings](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml#L256-L266) that are in need of translating if you had time to submit a PR.

**Comment by lucascaton** [comment]
@mmistakes sure thing! https://github.com/mmistakes/minimal-mistakes/pull/1278

**Pull request closed without merging**
