### PR TITLE
Add `wide` variant to single layout

### PR DESCRIPTION
**Pull request by peterahrens**
This pull request adds a new layout called "queen." It is a wider version of "single" (yes like the mattress sizes). It puts the right sidebar on top (if you asked for a right sidebar) so that you can get that sweet sweet wide display you've been craving for your programming blog post (80 characters or bust!), without cramping your style in your more literary blog posts. I don't really know if this layout is really worth merging, but I thought I would put it here so somebody might copy what I did instead of bugging mmistakes about widening the margins again.

### CODE REVIEW

**Comment by peterahrens** [comment]
honestly, I am just going to close this and some diligent github user might read it later.

**Comment by mmistakes** [comment]
The elegant approach here is to utilize the `classes` front matter instead of adding a new `layout`.

For a page you'd want the wide variant of you'd do something like:

```yaml
---
layout: single
classes: wide
---
```

Which would put a `wide` class on the [`<body>`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/default.html#L17) element. You could then and similar CSS to what you did but using `.wide` to override the page and sidebar classes.

```scss
.wide {
  
  .page {
    // override right padding and width's to make wide
  }

  .sidebar__right {
    // override negative margin, width, positioning, etc.
  }

  // any other overrides needed for a wide `.page`
}
```

**Comment by mmistakes** [comment]
If you want to take a stab at this I'll review it and see about getting it merged in.

**Comment by mmistakes** [comment]
Looks good @peterahrens, thanks for making the change and resubmitting.

**Comment by peterahrens** [comment]
Thanks for the tips @mmistakes!

**Comment by peterahrens** [comment]
Hopefully this helps with issues like #1480, #1373, #1265, #384, #136, and #74.

**Comment by ohadschn** [comment]
Do you guys have a live demo for this?

**Comment by mmistakes** [comment]
https://mmistakes.github.io/minimal-mistakes/markup-text-readability-wide-page/

**Comment by ohadschn** [comment]
Nice!
Apologies for my laziness, I should have checked your sample post list - comprehensive as always :)

**Comment by dongdongbh** [comment]
I add classes: wide to post, but it didn't work? I didn't use toc, and use same ccs file as the master branch

**Pull request merged**
