### PR TITLE
Add option to anonymize analytics ip address

### PR DESCRIPTION
**Pull request by 4brunu**
Hey,
I would like to anonymize the analytics ip address.
Since I didn't find any option to do it, I created it.
Let me know if more changes are required.
Thanks

### CODE REVIEW

**Comment by coliff** [comment]
It'd be good to add this for the Google gtag.js analytics integration too:
REF: https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization

**Comment by 4brunu** [comment]
@coliff Thanks for the comment, it's done 🙂

**Comment by mmistakes** [comment]
Looks good @4brunu, thanks for the PR!

**Comment by 4brunu** [comment]
Thanks for accepting this 😄 
Do you have any plans for releasing a new version soon?
Thanks 👍

**Comment by mmistakes** [comment]
Yes. Just released a new version.
https://github.com/mmistakes/minimal-mistakes/releases/tag/4.11.2

**Comment by 4brunu** [comment]
Thanks! 👍

**Pull request merged**
