### PR TITLE
Add 'hide_site_title' flag to pages

### PR DESCRIPTION
**Pull request by lucascaton**
Hi there!

There are some pages that I don't want to have a title suffix, ie.: instead of `My Page - My Site`, I'd like to only have `My Page`.
Does it make sense? Please let me know if there's a better/easier way to do it :)

Cheers.

### CODE REVIEW

**Comment by mmistakes** [comment]
What problem does this PR propose to solve?

**Comment by lucascaton** [comment]
@mmistakes sorry - I should've been more clear :)

There are some pages that I don't want to have a title suffix, ie.: instead of `My Page - My Site`, I'd like to only have `My Page`. Does it make sense?

**Comment by mmistakes** [comment]
Makes sense. Seems like a niche use case and not something that would benefit most users of the theme, especially with it adding more complexity. 

Closing as this is best left as something you override/customize locally yourself.

**Comment by lucascaton** [comment]
@mmistakes I customized it locally already, I only submitted the PR in case it could help anyone else.

The only problem is that `_includes/seo.html` is a 166 LOC file and it's hard to remember to keep it in sync with its original file.

**Comment by lucascaton** [comment]
hey @JoshBeardJB - you can add it to any page, as long as it includes your HTML template.

For example, you can add it to the following `_pages/about.md` file:

```md
---
layout: single
title: About
permalink: /about/
hide_site_title: true
---

Your page content here.
```

Hope it helps :)

**Comment by JoshBeardJB** [comment]
Yes! Okay, I got it now @lucascaton - Thank you so much for taking the time to respond!

**Pull request closed without merging**
