### PR TITLE
Update video

### PR DESCRIPTION
**Pull request by gammell**
Fix comment tag.

### CODE REVIEW

**Comment by gammell** [comment]
Sorry for the confusion, my change is to remove the slash, not add it.

**Comment by mmistakes** [comment]
Gotcha, still don't think the slashes matter. You have a link to a repo where you're experiencing the issue.
Seems to be working fine for the demo site.

**Comment by gammell** [comment]
Unfortunately, there's no repo at the moment. I'm in the process of working through my various bugs, and while I figured it was unlikely that that comment was causing general problems, I thought I'd flag it since it was nonstandard.

Thanks for the great theme by the way.

**Comment by mmistakes** [comment]
OK. Closing for now. If you can reproduce and provide a repo I'm happy to look into it further.

**Pull request closed without merging**
